import { AlertTriangle } from "lucide-react";

const alerts = [
  {
    message: "SQL Injection detected",
    ip: "185.45.22.91",
    attack: "SQL Injection",
    severity: "High",
    status: "Active",
    time: "10:45:23",
  },
  {
    message: "Possible DDoS traffic spike",
    ip: "103.78.114.12",
    attack: "DDoS Attempt",
    severity: "Medium",
    status: "Active",
    time: "10:41:09",
  },
  {
    message: "Malware signature detected",
    ip: "91.210.55.17",
    attack: "Malware Activity",
    severity: "High",
    status: "Resolved",
    time: "10:37:16",
  },
  {
    message: "Port scanning detected",
    ip: "45.67.88.204",
    attack: "Port Scan",
    severity: "Low",
    status: "Resolved",
    time: "10:29:48",
  },
];

function severityColor(level) {
  if (level === "High") return "border-red-500/40 bg-red-500/10 text-red-300";
  if (level === "Medium") return "border-yellow-500/40 bg-yellow-500/10 text-yellow-300";
  return "border-green-500/40 bg-green-500/10 text-green-300";
}

function statusColor(status) {
  if (status === "Active") return "border-red-500/40 bg-red-500/10 text-red-300";
  return "border-emerald-500/40 bg-emerald-500/10 text-emerald-300";
}

export default function Alerts() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8">

      <h1 className="text-3xl font-bold mb-2">
        Security Alerts
      </h1>

      <p className="text-slate-400 mb-8">
        Real-time alerts generated by the IDS / IPS engine
      </p>

      <div className="rounded-xl border border-slate-800 bg-slate-900 p-6">

        <table className="w-full text-sm">

          <thead className="text-slate-400 border-b border-slate-800">
            <tr>
              <th className="py-3 text-left">Alert</th>
              <th className="text-left">Source IP</th>
              <th className="text-left">Attack Type</th>
              <th className="text-left">Severity</th>
              <th className="text-left">Status</th>
              <th className="text-left">Time</th>
            </tr>
          </thead>

          <tbody>

            {alerts.map((row) => (

              <tr key={row.ip} className="border-t border-slate-800">

                <td className="py-4 flex items-center gap-2 text-slate-200">
                  <AlertTriangle size={16} className="text-yellow-400"/>
                  {row.message}
                </td>

                <td>{row.ip}</td>

                <td>{row.attack}</td>

                <td>
                  <span className={`px-2 py-1 text-xs rounded border ${severityColor(row.severity)}`}>
                    {row.severity}
                  </span>
                </td>

                <td>
                  <span className={`px-2 py-1 text-xs rounded border ${statusColor(row.status)}`}>
                    {row.status}
                  </span>
                </td>

                <td>{row.time}</td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>

    </div>
  );
}